# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8553227eee99d70f7d9bdc226468d271bb2bab7902cd3925d834ea7e000d36f2870d576c97dd9a60f0739da005d59bdc48b6f7cce11476558dde04cef118ceb6

test:
  secret_key_base: 83c9b73eaa4f6016b8b81a900351669a1f65c36a6d2e6c1f435f3a6c480a6488d1b9b174af9a668432a4f2b41901f535e5b2fc167cc542ea1f945e918486fa9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
